### PR TITLE
Converting object to iframe

### PR DESCRIPTION
**Pull request by joefatora**
This fixes IE 11 and Firefox 68 crashing

### CODE REVIEW

**Comment by FezVrasta** [comment]
I wonder if the performance is the same, or if iframe is heavier?

**Comment by joefatora** [comment]
No discernible difference in perf, but I didn't do any profiling to verify. And by the time you add a browser check and whatever code that requires to make it reliable, this is probably an equally efficient solution to the conditional iframe solution described in the bug report.

**Comment by joefatora** [comment]
@FezVrasta are you going to accept this PR?

**Comment by FezVrasta** [comment]
Right now I'm abroad, once I get back home I'll find some time to look at it 👍

**Comment by FezVrasta** [comment]
Hey, sorry for the delay.

I'm not very confident with this solution, I fear an iframe is going to use a huge amount of resources on the browser...

I tried to reproduce the issue on Firefox 68.0.1 but everything seems to work just fine.

I would like to be able to reproduce the problem before I consider switching to a potentially performance intensive fix.

**Comment by ShanonJackson** [comment]
This fix is more for IE11, currently after swapping to this library recently from resize-observer-polyfill which has had different types of problems iv'e broken our production IE11 build; the fix has been cloneing the files locally to change to iframe myself which works fine.

Please approve

**Comment by newsiberian** [comment]
@FezVrasta, hi, can you please approve this?

**Comment by FezVrasta** [comment]
Ok let's try it out and see if anybody reports performance issues.

**Comment by SpadarShut** [comment]
Iframe doesn't have `data` attribute. It should be `src` instead. And also attributes `type="text/html"` and `frameBorder="0"` should go on the iframe too.

**Comment by FezVrasta** [comment]
@SpadarShut could you send a PR please?

**Comment by SpadarShut** [comment]
Made one. And I meant `type="text/html"` should be removed instead.

**Comment by jedwards1211** [comment]
I have a project where I use `react-measure` on each item in a virtualized list for automatic row heights...honestly I wonder if the `iframe` approach in this package would perform well enough for that. I doubt creating an entire browsing context is a lightweight operation.  Wouldn't be surprised if creating dozens of them causes the browser to choke a bit.

There is a resize observer polyfill you could use...https://github.com/que-etc/resize-observer-polyfill

**Comment by ShanonJackson** [comment]
Resize-oberserver and Resize-observer polyfill just sucks; It is very flakey just like all other methods of measuring changes to DOM. We've swapped between react-spring "auto" on their render props API -> resize-observer -> this and this is the most reliable method so far. Never fails all browser compliant.

**Comment by jedwards1211** [comment]
Huh, I see.  I really wish there were a standardized way of registering a JS function to perform the layout of a component's children, instead of responding to size changes after the fact...

**Pull request merged**
