### PR TITLE
chore: add TS typings

### PR DESCRIPTION
**Pull request by fxlrnrpt**

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks! It looks like the type is missing the customReporter argument

**Comment by fxlrnrpt** [comment]
> Thanks! It looks like the type is missing the customReporter argument

Oops... Sorry. I have copy-pasted it from the project where I did not use it. Let me update it.

**Comment by fxlrnrpt** [comment]
@FezVrasta added the `customReporter`

**Review by FezVrasta — APPROVED** [review]

**Comment by fxlrnrpt** [comment]
@FezVrasta would it be too much to ask to publish a new version?

**Pull request merged**
