### PR TITLE
Remove unusable, non-legible `aria-label`

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to remove the `aria-label` attribute from the rendered `iframe`. Because the `iframe` is already rendered with `aria-hidden`, it is removed from the accessibility tree and thus the `aria-label` would never be used. Furthermore, the label itself may or may not be readable in its current form, depending how well assistive technology interprets the dash of `"resize-listener"` (vs., say, `"resize listener"`).

References:

- https://stackoverflow.com/a/52841858
- https://a11y-guidelines.orange.com/web_EN/exemples/iframes-techniques/index.html
- https://wordpress.slack.com/archives/C02RP4X03/p1584717155024800 ([link requires registration](https://make.wordpress.org/chat/))

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks!

**Comment by aduth** [comment]
Thanks for merging this @FezVrasta . Any chance a release could be published which includes this change? It's come up again in our project at https://github.com/WordPress/gutenberg/issues/22864 .

**Comment by FezVrasta** [comment]
Done

**Comment by aduth** [comment]
Thanks for the quick turnaround! ❤️

**Comment by FezVrasta** [comment]
It only took 6 months 😂

**Comment by aduth** [comment]
Hah! Well, just to be clear, I meant between my follow-up and the release 😉 

It's appreciated all the same.

**Pull request merged**
